package com.ctrip.util;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class LeetCodeRandomOne {
    //98(二叉搜索树 repeat)、720(前缀树)、485(数组)、692(堆)、152(动态规划)、22(回溯算法)、二叉树
    public static void main(String[] args) {
        System.out.println(getOne());
    }

    public static String getOne(){
        List<String> list = new ArrayList<>();
        list.add("17");
        list.add("22");
        list.add("485");
        list.add("283");
        list.add("27");
        list.add("203");
        list.add("206");
        list.add("933");
        list.add("622");
        list.add("641");
        list.add("20");
        list.add("496");
        list.add("217");
        list.add("389");
        list.add("705");
        list.add("215");
        list.add("692");
        list.add("141");
        list.add("344");
        list.add("881");
        list.add("704");
        list.add("35");
        list.add("162");
        list.add("74");
        list.add("209");
        list.add("1456");
        list.add("509");
        list.add("206");
        list.add("344");
        list.add("687");
        list.add("169");
        list.add("78");
        list.add("77");
        list.add("46");
        list.add("938");
        list.add("78");
        list.add("200");
        list.add("102");
        list.add("107");
        list.add("103");
        list.add("547");
        list.add("721");
        list.add("322");
        list.add("1217");
        list.add("55");
        list.add("509");
        list.add("62");
        list.add("121");
        list.add("70");
        list.add("279");
        list.add("207");
        list.add("210");
        list.add("208");
        list.add("720");
        list.add("1");
        list.add("4");
        list.add("15");
        list.add("75");
        list.add("76");
        list.add("19");
        list.add("24");
        list.add("25");
        list.add("142");
        list.add("160");
        list.add("206");
        list.add("150");
        list.add("225");
        list.add("232");
        list.add("239");
        list.add("703");
        list.add("1047");
        list.add("151");
        list.add("541");
        list.add("18");
        list.add("49");
        list.add("242");
        list.add("94");
        list.add("101");
        list.add("102");
        list.add("104");
        list.add("105");
        list.add("114");
        list.add("236");
        list.add("98");
        list.add("17");
        list.add("22");
        list.add("39");
        list.add("46");
        list.add("78");
        list.add("79");
        list.add("226");
        list.add("98");
        list.add("11");
        list.add("55");
        list.add("122");
        list.add("328");
        list.add("309");
        list.add("406");
        list.add("714");
        list.add("36");
        list.add("34");
        list.add("79");
        list.add("191");
        list.add("120");
        list.add("152");
        list.add("300");
        int len = list.size() - 1;
        int randomNum = new Random().nextInt(len);
        return list.get(randomNum);
    }
}
