orderitemid,
       orderid,
       amount,
       orderdate as ordertime,
       ordertime as orderdate,
       orderhour,
       orderstate as orderstatus,
       quantity,
       productid,
       productname,
       resourceid,
       resourcename,
       finishdate as finishtime,
       finishtime as finishdate,
       bussinesstype,
       categorygroup,
       categoryid,
       categoryname,
       viewspotid,
       viewspotname,
       status,
       businessregionname,
       channel_name,
       subchannel_name,
       isdomestic,
       sid,
       allianceid,
       cityid,
       cityname,
       provinceid,
       provincename,
       countryid,
       countryname,
       uid,
       usedate as usetime,
       usetime as usedate,
       distributionchannelid,
       distributionchannelname,
       sub_butypename,
       cost,
       apptype,
       pay_ords,
       pay_price,
       pay_quantity,
       profit,
       refund_ords,
       refund_price,
       refund_quantity,
       activity_type,
       vendorid,
       vendorname,